### ISSUE TITLE
Não foi possível autorizar o módulo, por favor repita o processo.

### ISSUE THREAD

**Issue by marcelowu** [elisei/moip-transparente-prestashop#4]
Não foi possível autorizar o módulo, por favor repita o processo.
versao 1.6.1.7 
conta fisica
 sandbox

**Comment by elisei** [comment]
Oi Marcelo, 
Nesse caso precisar criar uma conta do tipo vendedor no sandbox:
bem-vindo-sandbox.moip.com.br

**Comment by marcelowu** [comment]
conta tinha criado...no woo funciona..
