### ISSUE TITLE
Exibir informações da transação na tela do pedido

### ISSUE THREAD

**Issue by brunobincoletto** [elisei/moip-transparente-prestashop#5]
Tenho alguns clientes que reclamaram de não ter algumas informações da transação na tela do pedido no backoffice.

1. Número de parcelas que o cliente selecionou
2. Taxa da transação
3. Código da transação

**Comment by elisei** [comment]
Olá @brunobincoletto  tais recursos já estão disponíveis desde o último commit, detalhes dos pedidos:
https://i.imgur.com/a1kEnQG.png
https://i.imgur.com/dMPGDH8.png
