### ISSUE TITLE
Boletos Registrados

### ISSUE THREAD

**Issue by brunobincoletto** [elisei/moip-transparente-prestashop#7]
Enviar CPF para boletos registrados.

Verificar se existe um número do cpf nas tabelas:

prefix_customer - vat_number (muitos convertem esse campo para cpf)
prefix_customer - doc (algunus módulos criam essa tabela)
prefix_djtalbrazilianregister - esse módulo cria duas colunas uma para cpf e outra para cnpj
e verificar o campo que o FKcustomer também cria, não lembro a tabela de cabeça.

Se existir o documento em algum desses campos, deixar o input com o value já preenchido, se não existir deixar em branco e requisitar ao cliente via validação.

**Comment by elisei** [comment]
Olá @brunobincoletto 
O módulo já faz verificação para vat_number, document e cpf_cnpj você pode ver mais detalhes do processo aqui: https://github.com/elisei/moip-transparente-prestashop/blob/master/moipv2/controllers/front/authorization.php#L318-L337
No entanto não produtivo colocarmos total e qualquer variação possível geradas por módulos de terceiros, em caso de personalização nas lojas por tais módulo entendo como necessário também personalizar o método de pagamento.
