### ISSUE TITLE
CPF moip prestashop

### ISSUE THREAD

**Issue by minhavinheta** [elisei/moip-transparente-prestashop#8]
Olá tudo bem!!!

Estou com dificuldades em informar o CPF do usuário ao moip, estou usando o modulo moip transparente, poderia dar uma luz?

Att,

**Comment by elisei** [comment]
Olá @minhavinheta 
O módulo foi estruturado para capturar até 3 tipos de atributos defindos como cpf:
https://github.com/elisei/moip-transparente-prestashop/blob/master/moipv2/controllers/front/authorization.php#L318-L337
Atributo do customer-> cpf_cnpj
Atributo do customer -> document
Atributo de endereço -> vat_number
Caso seu atributo não seja nenhum desse precisa consultar seu dev para personalizar as linhas indicadas para captura do seu dado.

**Comment by minhavinheta** [comment]
Bom dia!

Para estes atributos acima, vc esta utilizando o módulo FK correto? é que no meu caso uso o modulo "cadastro brasileiro", será que é este o problema?

Obrigado!
Att,


Em seg, 10 de set de 2018 às 10:02, Bruno <notifications@github.com<mailto:notifications@github.com>> escreveu:

Olá @minhavinheta<https://github.com/minhavinheta>
O módulo foi estruturado para capturar até 3 tipos de atributos defindos como cpf:
https://github.com/elisei/moip-transparente-prestashop/blob/master/moipv2/controllers/front/authorization.php#L318-L337
Atributo do customer-> cpf_cnpj
Atributo do customer -> document
Atributo de endereço -> vat_number
Caso seu atributo não seja nenhum desse precisa consultar seu dev para personalizar as linhas indicadas para captura do seu dado.

**Comment by elisei** [comment]
Olá @minhavinheta 

document e vat_number são atributos nativos da sua plataforma, já o cpf_cnpj é de fato gerado por módulo de terceiro, por isto basta seguir a lógica ai aplicada e informar qual o atributo gerado pelo módulo que usa, se for uma atributo associado ao customer $customer->name_do_atributo, se for de endereço $address->name_do_atributo.

Possivelmente o desenvolvedor do módulo que usa deverá ter alguma coisa em sua documentação para orienta-lo sobre qual é o atributo que foi gerado.

**Comment by minhavinheta** [comment]
Boa noite!

Bruno fiquei até agora tentando, realmente não condigo, tem como me
dar um forcinha não? mais ainda né....

Att,
Em seg, 10 de set de 2018 às 12:37, Bruno <notifications@github.com> escreveu:

**Comment by elisei** [comment]
Olá @minhavinheta 

Me encaminha o módulo que está usando que vejo na doc dele como capturar o dado.

**Comment by minhavinheta** [comment]
Bom dia!

Segue o link para download
https://clisen.com.br/djtalbrazilianregister.zip
mas não veio documentação dele!

Muito obrigado!
Att,

Em ter, 11 de set de 2018 às 10:34, Bruno <notifications@github.com<mailto:notifications@github.com>> escreveu:

Olá @minhavinheta<https://github.com/minhavinheta>

Me encaminha o módulo que está usando que vejo na doc dele como capturar o dado.

**Comment by elisei** [comment]
Me passe o endereço de sua loja também, há várias configurações possíveis no módulo, então preciso ver qual aplicou.

**Comment by minhavinheta** [comment]
o site é http://wakenavis.com.br/
Em ter, 11 de set de 2018 às 11:05, Bruno <notifications@github.com> escreveu:

**Comment by elisei** [comment]
@minhavinheta 

Nessa linha https://github.com/elisei/moip-transparente-prestashop/blob/master/moipv2/controllers/front/authorization.php#L319 troque:
$taxvat   = $customer->cpf_cnpj;
para:
$taxvat   = $customer->br_document;

**Comment by minhavinheta** [comment]
Fiz a alteração, e ainda não esta funcionando.

Em ter, 11 de set de 2018 às 12:12, Bruno <notifications@github.com<mailto:notifications@github.com>> escreveu:

@minhavinheta<https://github.com/minhavinheta>

Nessa linha https://github.com/elisei/moip-transparente-prestashop/blob/master/moipv2/controllers/front/authorization.php#L319 troque:
$taxvat = $customer->cpf_cnpj;
para:
$taxvat = $customer->br_document;

**Comment by elisei** [comment]
Olá @minhavinheta 

Por favor entre em contato com o prestashop@moip.com.br irá ser solicitado o acesso ftp e admin para verificarmos para você.
